name: tof-distance-tmf
author: niels
source: github.com/vu-ase/tof
version: 0.0.1
description: Reads distance frames from the TMF8829 time-of-flight sensor.

commands:
  build: make build
  run: ./bin/tof

inputs: []

outputs:
  - sensor-right
  - sensor-left

configuration:
  - name: mode
    type: number
    value: 0
    tunable: false
    # 0 = 8x8
    # 5 = 16x16
    # 8 = 32x32
    # 11 = 48x32

  - name: timeout
    type: number
    value: 0
    tunable: false
    # 0 means run forever.

  - name: confidence-threshold
    type: number
    value: 6
    tunable: true

  - name: period-ms
    type: number
    value: 200
    tunable: true

  - name: iterations
    type: number
    value: 1800
    tunable: false

  - name: short-iterations
    type: number
    value: 100
    tunable: false

  - name: debug
    type: number
    value: 1
    tunable: true
    # 0 = off, 1 = on